# Generated by Django 4.1.5 on 2023-01-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('strap_color', models.CharField(max_length=20)),
                ('highlights', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
